version: "3.9"

services:
  backend:
    container_name: app_backend_dev
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: npm run dev
    volumes: 
      - ./backend:/app-backend
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      APP_PORT: 3001
      DB_PORT: 5432
      JWT_SECRET: jwt_secret
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5

  db:
    image: postgres:latest
    container_name: db
    hostname: postgres
    platform: linux/x86_64
    ports:
      - 3002:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - ng_network
      - ng_db_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    networks:
      - ng_db_network

  prisma-postgres-api:
    stdin_open: true
    build: ./backend
    container_name: prisma-postgres-api
    depends_on:
      - db
    ports:
      - 3004:3001
    restart: always

volumes:
  postgres-data:
  pgadmin-data:

networks:
  ng_network:
  ng_db_network:
    driver: bridge