version: "3.9"

services:
  backend:
    container_name: app_backend_dev
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: npm run dev
    volumes: 
      - ./backend:/app-backend
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      APP_PORT: 3001
      JWT_SECRET: jwt_secret
    networks: 
    - connect-app

  db:
    image: postgres:latest
    container_name: db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    networks: 
    - connect-app

volumes:
  postgres-data:
  pgadmin-data:

networks:
  connect-app: