version: "3.9"

services:
  frontend:
    container_name: app_frontend_dev
    build: ./frontend
    ports:
       - 3000:3000
    depends_on:
       backend:
         condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    volumes: 
      - ./frontend:/app-frontend
  backend:
    container_name: app_backend_dev
    platform: linux/x86_64
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev
    volumes: 
      - ./backend:/app-backend
    environment:
      DATABASE_URL : postgresql://user:password@db:5432/database?schema=public
      APP_PORT: 3001
      JWT_SECRET: jwt_secret
    networks: 
      - connect-app
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5

  db:
    container_name: db
    platform: linux/x86_64
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks: 
      - connect-app
    healthcheck: # I will not put interval because my pc is weak
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 10s
      retries: 5
    restart: always

networks:
  connect-app:
