version: '3.9'

services:
  backend:
    container_name: app_backend
    build: ./backend
    platform: linux/x86_64
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL : postgresql://user:password@db:5432/database?schema=public
      APP_PORT: 3001
      JWT_SECRET: jwt_secret
    networks: 
      - connect-app
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5

  db:
    container_name: db
    platform: linux/x86_64
    image: postgres:latest
    ports:
      - 3002:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks: 
      - connect-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 10s
      retries: 5
    restart: always

networks:
  connect-app:
